### ISSUE TITLE
JavaScript examples

### ISSUE THREAD

**Issue by iliocatallo** [mattbierner/akh#26]
Hi,

I would like to ask if it is possible to double each example with its JavaScript counterpart (both in the website and the wiki). I'm confident AKH can prove very useful when coupled with the Folktale libraries, but I'm having a hard time following the examples because of the Khepri syntax.

Thanks.

**Comment by mattbierner** [comment]
Sure, I'll add es6 examples as later today. The lambda syntax was the main reason I originally wrote these in Khepri.

**Comment by iliocatallo** [comment]
Thank you for changing the quick example. In this regard, probably there is no more need in the README.md for the sentence:

> Example is in Khepri but regular js works fine too.
