### ISSUE TITLE
M.liftInner()

### ISSUE THREAD

**Issue by iliocatallo** [mattbierner/akh#27]
Hi,

according to the documentation, monad constructors resulting from transformations should be equipped with the `liftInner()` method. I did the following:

    let EitherT = require('akh').trans.either,
        Task = require('data.task'),
        EitherTask = EitherT(Task);

Given the following function:
    
    let getGreetings = name => Task.of('hey: ' + name);

I would expect to be able to lift `getGreetings` by doing:

    EitherTask.liftInner(getGreetings);

Unfortunately, on node 5.0.0 I get:

    TypeError: EitherTask.liftInner is not a function

Am I missing something?

Thanks!

**Comment by mattbierner** [comment]
`liftInner` only works if the inner type (`Task` in this case) is also a monad transformer and it defines a method called `lift`. 

In this case, since `Task` is a regular type and not a monad transformer, you probably want `EitherTask.lift` instead. But because you want to lift the Task itself, `lift` needs to be composed with the `getGreetings` function:

```js
let getGreetings = name => EitherTask.lift(Task.of('hei: ' + name));
```

Let me know if that is incorrect.

**Comment by iliocatallo** [comment]
I had the chance to reflect more on this issue. I'm sorry if this is trivial, but I'm rather new to Monad Transform

My objective is to account for the case in which an asynch. computation may fail (either because of the absence of sensible values, or because of a failure in the computation iself).  To this end, let us consider the following function:

    let getUserById = id => id !== 1 ? Task.of({_id: id}) : Task.of(null);

`getUserById` simulates an asynchronous access to a data store. Accessing the db may result in `null`, which represent the fact that the query led to no results (ideally, I would like to use native Promises in lieu of Tasks, but since they are only monad-like objects they don't mix well with actual monads). 

At this point I would like to apply the `Either` context on the result of the asynch. computation. Something like:

    let toEither = userTask => userTask.map(user => !user ? Either.left() : Either.right(user));

At the calling site, I would  like the result of `toEither . getUserById` to exhibit a `Either` interface. To this end, let us apply the `EitherT` on `Task`.

    let EitherTask = EitherT(Task);

And then:

   let eitherUser = new EitherTask(toEither(getUserById(0))),
       eitherId = eitherUser.map(u => u._id);

At this point I would like to fire the underlying asynch. operation. Something like:

    eitherId.run.fork(err => console.log('the db exploded!'), id => console.log(id));

Unfortunately, the above does not work. How (if possible) can I achieve this result?

Thanks and sorry for slightly abusing the bug reporting system.

**Comment by mattbierner** [comment]
No problem, always glad to help.

First off, I believe that `Data.Task` may not be the best fit for `EitherT. Task already has the concept of accepted or rejected values, so wrapping in a second layer of either values may be redundant.

But let's just assume that we do want an `EitherT(Task)` (the same approach can applied to `StateT` or any other transformers.) 

First declare the target type:

```js
const EitherT = require('akh').trans.either;
const Task = require('data.task');

const EitherTask = EitherT(Task);
```

And here's the `Task` operation that we want to perform (note that I've added `rejected` for ids that are less than zero`.

```js
const getUserById = id => (id >= 0 ? Task.of({_id: id}) : Task.rejected(null));
```

`getUserById ` operates on tasks directly, but in this case you really want an `EitherTask` that performs the same operation as `getUserById`. So we have to `lift` computation of an inner `Task` type into a computation of the `EitherTask` using `EitherTask.lift`.

```js
const eitherUser = EitherTask.lift(getUserById(2));
const eitherId = eitherUser.map(u => u._id);
```

`eitherUser` is translated by `lift` to:

```js
// Expansion of `EitherTask.lift(getUserById(2))`
getUserById(2).chain(x => Task.of(Right(x)));
```

The expansion of `lift` also shows how `EitherT` operates. `EitherT(Task)` just updates `Task` to operate on `Either` values. That `EitherT` puts `Either` values inside of the target monad is the reverse of what the notation `EitherT(Task)` would seem to suggest.

One other note: while it is true that Akh implements its monad transformers using Javascript functions and classes, this is an implementation detail that should not be relied on. Never try to call `new EitherTask` or anything like that.


Now for running the computation. Again `.run` is an implementation detail of Akh and should not be used directly. The proper way to run the either transformer is with `EitherT.eitherT(m, leftCallback, rightCallback)`. But `EitherT.eitherT` does not actually run the entire computation, instead it returns an unwrapped `Task` that must then be run to fully complete the computation:

```js
const runEitherTask = (m, l, r) => 
   EitherT.eitherT(m, Task.rejected, Task.of)
       .fork(l, r);
```

Hope that helps.

**Comment by iliocatallo** [comment]
Thank you for the thoroughly answer. 

Regarding your comment on `Task`, I would like to reject asynch. computations in the sole case in which something happened out of my control (i.e., an actual *exceptional case*). To showcase this, let me write a more realistic version of `getUserById`:

    // getUserById :: String -> Task Error User
    let getUserById = id => new Task((reject, result) => {
        redisClient.get(id, (err, value) => {
            if (err) reject(err);
            result(value);
        });
    });
    
In the above example, the task gets rejected if there has been an actual failure in the asynch computation (because of an error in Redis). When instead the computation succededs, Redis returns a user from the database, where `null` is used to denote the absence of a value. 

My overall objective is to distinguish between a failure in the computation itself and the absence of a value in the database. In order to do so, I would like to wrap query results in a `Either`, thus resulting in a final value of type `Task Either User` (for the sake of readibility, I'm omitting the left side of `Task` and `Either`). 

At the same time, at the calling site it would be convenient to be able to treat the resulting type as a `Either`, i.e., to have `map` operating on the inner `Either`, rather than on the outer `Task`. If I got it right, this can be achieved by applying the `EitherT` transformers over the `Task` monad.

    let EitherTask = EitherT(Task);
         
After receving a `Task User` from `getUserById`, the first step would be to move a `Either` into the `Task`. As you suggest, this can be done using `lift`:

    let eitherUser = EitherTask.lift(getUserById(2));

While this would automatically take care of the async. computational context (in that rejected `Task`s will simply be ignored), it would allow `null` to be placed on the right-side on `Either`. Nevertheless, by doing so we managed to remove a direct call to `new EitherTask`, which we would like to treat as an implementation detail.

Thinking about that, one possible way to do it would be to define a function:

    let toEither = user => user ? EitherTask.right(user) : EitherTask.left(new Error('no user'));

and then 

	let eitherUser = EitherTask.lift(getUserById(2)).chain(toEither);

We are now ready to project the `id` and trigger the `Task`:

    let eitherId = eitherUser.map(u => u.id);
    EitherT.eitherT(eitherUser, Task.rejected, Task.of)
           .fork(err => console.log(err), id => console.log(id));

Now we have that `err` might be either the error resulting from a failure in the asynch. computation or the error contained in the left side of the `Either`.
However, once again, the problem probably seems to stem from the absence of `EitherTask#innerLift`. Ideally, I would like to do:

    let toEither = user => user ? Either.right(user) : EitherTask.right(new Error('no user'));
    
and then:

	 let eitherUser = EitherTask.lift(getUserById(2)).chain(EitherTask.innerLift(toEither));


How can I overcome the absence of `EitherTask.innerLift`? 

Thank you!

P.S. with respect to `new EitherTask` and `EitherTask#run` being implementation details, I've probably been fooled by their Haskell counterparts. Indeed, the `Task Either` contained in the `EitherTask` is commonly named `run`. The constructor and the record-generated function `run` are then used to, resp., wrap and unwrap the inner `Task Either` value.

**Comment by mattbierner** [comment]
If I understand correctly, the problem is mapping between the inner `Either` value and the top level `Task` so that you can distinguish: success cases, no value cases, and computational error cases (such as the DB being down).

`EitherT` does not have any knowledge of the specific type it is transforming, so you must provide this mapping manually with a `run` function. Here's what the mapping function may look like:

```js
EitherT.eitherT(eitherUser,
    l => ({ value: l, left: true }),
    r => ({ value: r, right: true })
).fork(
    err => {
        console.log('System Error: ', err)
    },
    x => {
        if (x.left) {
              console.log('Value error', x.value);
        } else {
              console.log("OK:", x.value)
        }
    });
```


I believe that this correctly handles all the cases.

Haskell provides this through `EitherT.runEitherT` and I'll add `runEitherT` in  Akh 2.1 so that you only have to write: `EitherT.runEitherT(eitherUser).fork(...)`



As for `liftInner`, it is only applicable when dealing with a stack of monad transformers. Consider this stack:

```js
const M = EitherT(StateT(Cont));
``` 

We can perform state operations within `M` by calling `lift` directly:

```js
const M_get = M.lift(StateT(Cont).get);
// Or
const M_get = M.lift(M.inner.get);
```

But to call `callcc` on `Cont`, we have to lift through two levels:

```js
const M_callcc = f => M.lift(StateT(Cont).lift(Cont.callcc(f)));
// Or
const M_callcc = f => M.lift(M.inner.lift(Cont.callcc(f)));
```

`liftInner` simplifies lifting through multiple levels by allowing us to write:

```js
const M_callcc = f => M.liftInner(Cont.callcc(f));
```

In you case, since there is only a single transformer, `liftInner` is not defined. `lift` is the only operation you need.

**Comment by iliocatallo** [comment]
Once again, thanks for your careful answer. 

I had the time to thing again about this issue. As much as I like the idea of being able to precisely distinguish between the different cases I was mentioning, the syntatic noise is too much to produce concise code. 

All in all, I think your original advice of chaining Task/Promises represents the best trade-off. In particular, native Promises allow me to use `do`-like notation through libraries such as `co` and to avoid stacking too much context. 

Anyhow, it is great to see a solid monad transformer library that enables the use of (advanced) functional patterns in JavaScript.  If I may, I would suggest to consider re-writing Akh in ES6, now that it made into node 4+.  Moreover, it is somehow a pity to have this use case buried into the bug system. Maybe it can be extracted and proposed as an example.

I'm looking forward to Akh 2.1.
Thanks again for your help.

**Comment by mattbierner** [comment]
Rewritten with Es6 with V3, which also split the library up into multiple packages. Take a look any let me know if you run into any problems or have any suggestions.
