### ISSUE TITLE
Do notation

### ISSUE THREAD

**Issue by jmatsushita** [mattbierner/akh#31]
Hi there,

I'm discovering the fantasy land ecosystem and i was wondering if Akh would work with fantasy-do and how would lifting work?

Cheers,

Jun

**Comment by mattbierner** [comment]
yes, it should work:

```js
const mdo = require('fantasy-do')
const Maybe = require('akh').Maybe

const div = (a, b) => (b === 0) ? Maybe.nothing : Maybe.just(a / b)

const result = Maybe.run(mdo(function* () {
    const a = yield div(8, 2)
    b = a + 2
    return div(b, 2)
}))

console.log(result)
```

Haven't tried it more extensively so let me know if you run into any issues.


Can you explain your question/concern about lifting a bit more please?

**Comment by jmatsushita** [comment]
Ah great to hear ! Thanks for the example, I'll give it a whirl.

By lifting I mean being able to call the operations of outer monads in the stack from within a do block.

This would be an example in Haskell: https://github.com/kqr/gists/blob/master/articles/gentle-introduction-monad-transformers.md#lifting

**Comment by mattbierner** [comment]
Yes, I believe that also should work. Here's a quick example I tested

```js
const mdo = require('fantasy-do')
const Maybe = require('akh').Maybe
const StateT = require('akh').StateT

const M = StateT(Maybe)

const run = (c, state) => Maybe.run(StateT.run(c, state))

const result = run(mdo(function* () {
    const a = yield M.lift(Maybe.just(2))
    b = a + 2
    return M.of(b)
}), 'wackyland')

console.log(result)
```

This prints:

```
{ just: true, value: { value: 4, state: 'wackyland' } }
```

Again, I haven't tested `fantasy-do` much directly so let me know if you run into any issues using it with akh

**Comment by mattbierner** [comment]
Closing out since I haven't heard anything back on this. Please let me know if you run into any issues or have any other questions about the library
